"""added unique for channel_message_stats

Revision ID: 0f00fda3f5d1
Revises: 7d1fb27e8b3d
Create Date: 2026-03-18 09:39:53.155008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f00fda3f5d1'
down_revision: Union[str, Sequence[str], None] = '7d1fb27e8b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_message_stats', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('channel_message_stats', 'message_text',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'-'::character varying"))
    op.alter_column('channel_message_stats', 'views',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint('uq_channel_message_stats_channel_message', 'channel_message_stats', ['channel_id', 'message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_channel_message_stats_channel_message', 'channel_message_stats', type_='unique')
    op.alter_column('channel_message_stats', 'views',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('channel_message_stats', 'message_text',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'-'::character varying"))
    op.alter_column('channel_message_stats', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    # ### end Alembic commands ###
