"""added stats storage

Revision ID: 7d1fb27e8b3d
Revises: 46e9e6d312b7
Create Date: 2026-03-18 09:08:31.395954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1fb27e8b3d'
down_revision: Union[str, Sequence[str], None] = '46e9e6d312b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_message_stats',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(length=50), server_default='text', nullable=False),
    sa.Column('message_text', sa.String(), server_default='-', nullable=False),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reactions', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_message_stats_channel_id'), 'channel_message_stats', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_message_stats_message_id'), 'channel_message_stats', ['message_id'], unique=False)
    op.create_table('channel_metrics_snapshot',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('subscribers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_reach', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_engagement', sa.Integer(), server_default='0', nullable=False),
    sa.Column('er', sa.Float(), server_default='0', nullable=False),
    sa.Column('joins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('leaves', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_metrics_snapshot_channel_id'), 'channel_metrics_snapshot', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_metrics_snapshot_channel_id'), table_name='channel_metrics_snapshot')
    op.drop_table('channel_metrics_snapshot')
    op.drop_index(op.f('ix_channel_message_stats_message_id'), table_name='channel_message_stats')
    op.drop_index(op.f('ix_channel_message_stats_channel_id'), table_name='channel_message_stats')
    op.drop_table('channel_message_stats')
    # ### end Alembic commands ###
