"""initial

Revision ID: b3cabaeffd39
Revises: 
Create Date: 2026-03-18 07:39:30.637615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cabaeffd39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_daily_stats',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('joins_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('leaves_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_daily_stats_channel_id'), 'channel_daily_stats', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_daily_stats_channel_id'), table_name='channel_daily_stats')
    op.drop_table('channel_daily_stats')
    # ### end Alembic commands ###
