
services:
  db:
    image: postgres:17
    container_name: db_stats
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
#    ports:
#      - "5432:5432"
    env_file:
      - ./bot/.env

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin_stats
    ports:
      - "8180:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ../logs/pgadmin:/var/log/pgadmin
    restart: unless-stopped
    env_file:
      - ./bot/.env

  bot:
    build:
      context: .
      dockerfile: DockerfileBot
      args:
        - --no-cache
    container_name: bot_stats
    volumes:
      - ./bot:/app
      - ./logs/:/app/logs
#    restart: unless-stopped
    env_file:
      - ./bot/.env

volumes:
  postgres_data:
  pgadmin_data: